language: python

python:
    - "2.6"
    - "2.7"

env:
    - DB=sqlite DJANGO=1.3.7
    - DB=sqlite DJANGO=1.4.5
    - DB=sqlite DJANGO=1.5
    - DB=postgresql DJANGO=1.3.7
    - DB=postgresql DJANGO=1.4.5
    - DB=postgresql DJANGO=1.5

install:
    - pip install -q Django==$DJANGO pisa reportlab html5lib BeautifulSoup psycopg2==2.4.1 xlwt==0.7.4 --use-mirrors

before_script:
  - psql -c 'create database model_report;' -U postgres

script:
    - cd example && python manage.py test app --settings=test_project.settings_$DB --noinput

notifications:
  email:
    recipients:
      - jpma55@gmail.com
    on_success: always
    on_failure: always
